#!/bin/bash -e

CONFIG=$1
if [ -z "${CONFIG}" ]; then
    echo "Usage: $0 <config.cfg>"
    exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${SCRIPT_DIR}"

uv run ./openconnect-gp-okta.py --config ${CONFIG}
